In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("train.txt",sep=';',header=None,names=['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [6]:
emotion_counts = df['emotion'].value_counts()
print(emotion_counts)

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [7]:
unique_emotions = df['emotion'].unique()
emotion_numbers={}
i=0
for emo in unique_emotions:
  emotion_numbers[emo]=i
  i+=1
df['emotion']=df['emotion'].map(emotion_numbers)

In [8]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

**Text Cleaning**

In [9]:
 df['text']=df['text'].apply(lambda x: x.lower())

In [10]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

Removing Punctiation

In [11]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [12]:
df["text"]=df["text"].apply(remove_punc)

Removing numbers

In [13]:
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new=new+i
  return new
df["text"]=df["text"].apply(remove_numbers)

Remove Emoji's

In [14]:
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
      new=new+i
  return new

df["text"]=df["text"].apply(remove_emojis)

Remove Stopwords

In [15]:
import nltk

In [16]:
 from nltk.corpus import stopwords
 from nltk.tokenize import word_tokenize

In [17]:
nltk.download("punkt")
nltk.download("stopwords")
# punkt is a pre-trained sentence and word tokenizer.
#It helps NLTK split text into:

# Sentences
# Words

# It uses language-specific punctuation rules to perform
#accurate tokenization.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [18]:
 stop_words=set(stopwords.words("english"))
 stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [19]:
len(stop_words)

198

In [20]:
df.loc[1]["text"]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [21]:
#now remove stop words from text
def remove(txt):
  #words=word_tokenize(txt)
  words=txt.split()
  cleaned=[]
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return " ".join(cleaned)

In [22]:
df["text"]=df["text"].apply(remove)

In [23]:
df.loc[1]["text"]

'go feeling hopeless damned hopeful around someone cares awake'

In [24]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [25]:
df.shape

(16000, 2)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x=df["text"]
y=df["emotion"]

In [28]:
x

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...
15995        brief time beanbag said anna feel like beaten
15996    turning feel pathetic still waiting tables sub...
15997                             feel strong good overall
15998                       feel like rude comment im glad
15999                         know lot feel stupid portray
Name: text, Length: 16000, dtype: object

In [29]:
y

0        0
1        0
2        1
3        2
4        1
        ..
15995    0
15996    0
15997    5
15998    1
15999    0
Name: emotion, Length: 16000, dtype: int64

In [30]:
x=df["text"]
y=df["emotion"]

Then, `x` and `y` were split into training and testing sets using `train_test_split`:

In [31]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [32]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [33]:
y_train

676      5
12113    0
7077     2
13005    0
12123    1
        ..
13418    4
5390     2
860      0
15795    0
7270     1
Name: emotion, Length: 12800, dtype: int64

In [34]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

Converting text into vectorize forms

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [36]:
bow_vectorizer=CountVectorizer()
tfidf_vectorizer=TfidfVectorizer()

In [37]:
X_train_bow=bow_vectorizer.fit_transform(X_train)
X_test_bow=bow_vectorizer.transform(X_test)

In [38]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116059 stored elements and shape (12800, 13361)>

In [39]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26936 stored elements and shape (3200, 13361)>

Now, we Implement the ML models

In [40]:
#Applying Multinomial Naive bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report

In [41]:
nb_model=MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [42]:
pred=nb_model.predict(X_test_bow)

In [43]:
print("==============Accuracy using BoW===================")
print(accuracy_score(y_test,pred))
print("==============Classification Report===================")
print(classification_report(y_test,pred))
print("==================Thank you===========================================")

==============Accuracy using BoW===================
0.768125
==============Classification Report===================
              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.27      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

==================Thank you===========================================

Applying Logistic ML Models

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
logistic_model=LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_bow,y_train)

LogisticRegression(max_iter=1000)

In [46]:
pred=logistic_model.predict(X_test_bow)

In [47]:
print("==============Accuracy using BoW===================")
print(accuracy_score(y_test,pred))
print("==============Classification Report===================")
print(classification_report(y_test,pred))
print("==================Thank you===========================================")

==============Accuracy using BoW===================
0.8896875
==============Classification Report===================
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.89      0.86      0.87       427
           2       0.85      0.76      0.80       296
           3       0.86      0.73      0.79       113
           4       0.86      0.84      0.85       397
           5       0.88      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200

==================Thank you===========================================

Now, implementing Tf-Idf

In [48]:
tfidf_vectorizer=TfidfVectorizer()
X_train_tfidf=tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf=tfidf_vectorizer.transform(X_test)

Applying Naive Bayes ML Model

In [49]:
nb_model_2=MultinomialNB()
nb_model_2.fit(X_train_tfidf,y_train)

MultinomialNB()

In [50]:
pred=nb_model_2.predict(X_test_tfidf)

In [51]:
print("==============Accuracy using TF-IDF===================")
print(accuracy_score(y_test,pred))
print("==============Classification Report===================")
print(classification_report(y_test,pred))
print("==================Thank you===========================================")

==============Accuracy using TF-IDF===================
0.6609375
==============Classification Report===================
              precision    recall  f1-score   support

           0       0.70      0.93      0.80       946
           1       0.93      0.29      0.44       427
           2       1.00      0.03      0.06       296
           3       1.00      0.01      0.02       113
           4       0.92      0.22      0.36       397
           5       0.60      0.99      0.74      1021

    accuracy                           0.66      3200
   macro avg       0.86      0.41      0.40      3200
weighted avg       0.76      0.66      0.58      3200

==================Thank you===========================================

Applying Losgistic ML Models

In [52]:
from sklearn.linear_model import LogisticRegression

In [53]:
logistic_model=LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [54]:
pred=logistic_model.predict(X_test_tfidf)

In [55]:
print("==============Accuracy using TF-IDF===================")
print(accuracy_score(y_test,pred))
print("==============Classification Report===================")
print(classification_report(y_test,pred))
print("==================Thank you===========================================")

==============Accuracy using TF-IDF===================
0.8628125
==============Classification Report===================
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       946
           1       0.90      0.81      0.86       427
           2       0.90      0.61      0.73       296
           3       0.88      0.47      0.61       113
           4       0.86      0.76      0.81       397
           5       0.81      0.96      0.88      1021

    accuracy                           0.86      3200
   macro avg       0.88      0.76      0.80      3200
weighted avg       0.87      0.86      0.86      3200

==================Thank you===========================================

Applying User Input for sentiment Analysis

In [56]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Ensure NLTK resources are downloaded
import nltk
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower() # Convert to lowercase
    text = text.translate(str.maketrans('', '', string.punctuation)) # Remove punctuation
    text = re.sub(r'\d+', '', text) # Remove numbers
    text = ''.join(char for char in text if char.isascii()) # Remove non-ascii (emojis)
    words = text.split() # Split into words (similar to how stopwords were removed)
    cleaned_words = [word for word in words if word not in stop_words] # Remove stopwords
    return ' '.join(cleaned_words)

In [57]:
def predict_emotion(user_text):
    preprocessed_text = preprocess_text(user_text)
    # Transform the text using the trained TF-IDF vectorizer
    user_text_tfidf = tfidf_vectorizer.transform([preprocessed_text])

    # Predict the emotion using the trained Logistic Regression model
    prediction_numeric = logistic_model.predict(user_text_tfidf)

    # Map the numeric prediction back to the original emotion label
    # Invert the emotion_numbers dictionary to map numbers back to emotions
    emotion_labels = {v: k for k, v in emotion_numbers.items()}
    predicted_emotion = emotion_labels[prediction_numeric[0]]

    return predicted_emotion

In [62]:
from ipywidgets import Text, Output
from IPython.display import display

text_input = Text(description='Enter text:')
output_area = Output()

def on_text_change(change):
    with output_area:
        output_area.clear_output()
        user_input = change['new']
        if user_input:
            sentiment = predict_emotion(user_input)
            print(f'Your text: "{user_input}"')
            print(f'Predicted emotion: {sentiment}')

text_input.observe(on_text_change, names='value')
display(text_input, output_area)

Text(value='', description='Enter text:')

Output()

## Save and Load the Trained Model

In [63]:
import joblib

# Define filenames for saving the model and vectorizer
model_filename = 'logistic_model_tfidf.joblib'
vectorizer_filename = 'tfidf_vectorizer.joblib'

# Save the trained logistic regression model (with TF-IDF)
joblib.dump(logistic_model, model_filename)
print(f'Logistic Regression model saved as {model_filename}')

# Save the TF-IDF vectorizer
joblib.dump(tfidf_vectorizer, vectorizer_filename)
print(f'TF-IDF vectorizer saved as {vectorizer_filename}')

Logistic Regression model saved as logistic_model_tfidf.joblib
TF-IDF vectorizer saved as tfidf_vectorizer.joblib

In [64]:
# Load the model and vectorizer
loaded_model = joblib.load(model_filename)
loaded_vectorizer = joblib.load(vectorizer_filename)

print(f'Model loaded: {loaded_model}')
print(f'Vectorizer loaded: {loaded_vectorizer}')

Model loaded: LogisticRegression(max_iter=1000)
Vectorizer loaded: TfidfVectorizer()